### ISSUE TITLE
New Attack from a Weapon?

### ISSUE THREAD

**Issue by nskins** [gintavang/Ostrichland#23]
Maybe Weapons should have a member variable 'attack' that defines the Attack that it adds to the Player/Entity's possible attacks? Currently after equipping a Weapon, the Player only can Kick.

**Comment by nskins** [comment]
Also, Kick does additional damage even when a Weapon is equipped. Maybe the new Weapon should replace Kick with a completely different Attack, instead of just adding a new one?

**Comment by gintavang** [comment]
Not entirely sure what you mean by the second comment. I was thinking that the weapon adds an attack, which accounts for the increase in strength to the character. So rather than the weapon having a 'power' member variable, it just has an attack (or attacks) associated with it that have a 'damage' member variable, which will account for the increase in strength.

**Comment by nskins** [comment]
That sounds good; the only problem is that we'd have to use a different attack for every weapon or else every weapon with the attack will do the same damage. But this seems to be the best way to proceed for now.

**Comment by gintavang** [comment]
Ah, good point. Maybe we keep the power variable and make that a multiplier for the attack strength. That way it's the same attack, just with varying strengths for each weapon
